from .turno_serializer import TurnoSerializer
from .peluquera_serializer import PeluqueraSerializer
from .servicio_serializer import ServicioSerializer
from .cliente_serializer import ClienteSerializer